AWSTemplateFormatVersion: "2010-09-09"
Description: 'Public Subnets in ap-southeast-1 Custom VPC'
Resources:
  CustomVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '192.168.0.0/16'
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
        - Key : "Name"
          Value: "CustomVPC"

  publicSubnet1:
    Type : AWS::EC2::Subnet
    Properties: 
      AvailabilityZone : "ap-southeast-1a"
      CidrBlock : "192.168.1.0/24" 
      MapPublicIpOnLaunch : true
      Tags : 
        - Key : "Name"
          Value : "publicSubnet1"
      VpcId : 
        !Ref CustomVpc

  publicSubnet2:
    Type : AWS::EC2::Subnet
    Properties: 
      AvailabilityZone : "ap-southeast-1b"
      CidrBlock : "192.168.2.0/24" 
      MapPublicIpOnLaunch : true
      Tags : 
        - Key : "Name"
          Value : "publicSubnet2"
      VpcId : 
        !Ref CustomVpc

  publicSubnet3:
    Type : AWS::EC2::Subnet
    Properties: 
      AvailabilityZone : "ap-southeast-1c"
      CidrBlock : "192.168.3.0/24" 
      MapPublicIpOnLaunch : true
      Tags : 
        - Key : "Name"
          Value : "publicSubnet3"
      VpcId : 
        !Ref CustomVpc